# Generated by Django 6.0.3 on 2026-03-07 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='interest_date',
            new_name='interest_rate',
        ),
    ]
