# Generated by Django 6.0.3 on 2026-03-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0002_rename_interest_date_customer_interest_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='emi_due_date',
            new_name='emi_due',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], max_length=20),
        ),
    ]
