# Generated by Django 6.0.3 on 2026-03-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0003_rename_emi_due_date_customer_emi_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='emi_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID')], default='PENDING', max_length=20),
        ),
    ]
